# .github/workflows/github-metrics.yml
name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:     # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TechyCSR
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_notable: yes
